services:
  postgres:
    image: postgres:17-alpine
    container_name: luypos-postgres
    environment:
      POSTGRES_DB: luypos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - luypos_postgres_data:/var/lib/postgresql/data

volumes:
  luypos_postgres_data:

