name: LuyPOS Notifications

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    types:
      - opened
      - closed
      - reopened

jobs:
  telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="-1003941994826" \
          -d message_thread_id="2" \
          -d text="🚀 LuyPOS Notification

Repository: ${{ github.repository }}
Event: ${{ github.event_name }}
Branch: ${{ github.ref_name }}
Author: ${{ github.actor }}"